services:
  - docker

language: generic

script:
  - docker build -t moderras/rssbot:$(date +%F) -f ./Dockerfile .
  - docker build -t moderras/rssbot:latest -f ./Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push moderras/rssbot:$(date +%F)
  - docker push moderras/rssbot:latest
